const codeContainer = require(`${__dirname}/code-container/container`);
const fs = require("fs-extra");
const path = require("path");
const { fork } = require('child_process');
const crypto = require('crypto');
const mongoClient = require('mongodb').MongoClient;
const MessagingService = require('../messaging-service');

console.log("[INFO] Initialize app-manager...");
const serviceName = process.env.SERVICE_NAME;
const messagingService = new MessagingService(serviceName);

// db settings
const mongoUrl = 'mongodb://localhost:27017';
const appsDb = 'apps';
const appsInfoCollection = 'info';

// Initialize database connection once
let db;
mongoClient.connect(mongoUrl, { useNewUrlParser: true }, function(err, client) {
    if(err) {
        console.error("[ERROR] Failed to connect to mongodb.");
        throw err;
    }
    db = client.db(appsDb);
});

// TODO: When initializing app-manager, app-manager checks database to see 
// if any apps already existed (zombie process). This happens when app-manager crashed abnormally

// Create logs directory for apps if not present
fs.ensureDirSync(`${__dirname}/logs`);
/**
 * This function saves the app info to the database
 * @param {string} topic mqtt topic
 * @param {string} appPath application executable path
 * @param {string} metadataPath metadata path
 * @param {string} pid application's pid
 */
function saveAppInfoToDB(topic, appPath, metadataPath, pid) {
    let result = db.collection(appsInfoCollection)
                    .insertOne({
                        "name": path.basename(appPath),
                        "topic": topic,
                        "pid": pid,
                        "pathPath": appPath,
                        "metadataPath": metadataPath
                    });
    if("writeConcernError" in result) {
        throw result["writeConcernError"];
    }
}

// Stores the process, topic, pid, appPath, and metadataPath in apps
// apps = {
//     "app-name": {
//         "app": instance-of-process,
//         "pid": application-process-pid,
//         "topic": topic, // application's id
//         "appPath": application-executable-path,
//         "metadataPath": application-metadata-path
//     }
// }
const apps = {};

/**
 * This function generates the topic for new coming app.
 * the topic is the id generated by mongodb
 * @param {string} appPath
 * @returns {string}
 */
function generateTopic(appPath) {
    // The fastest algorithm is sha1-base64
    // Reference: https://medium.com/@chris_72272/what-is-the-fastest-node-js-hashing-algorithm-c15c1a0e164e
    const hash = crypto.createHash('sha1');
    // use the timestamp to create topic
    let dirName = path.dirname(appPath).split(path.sep).pop();
    hash.update(dirName);
    return hash.digest('base64');
}

// When app-manager get appPath and metadataPath from platform-manager,
// app-manager will fork a process for executing new app.
messagingService.listenForEvent('app-deployment', message => {
    let appData = message.data;
    if(appData.appPath && appData.metadataPath) {
        codeContainer.setupAppRuntimeEnvironment(appData.appPath, appData.metadataPath)
            .then((newAppPath) => {
                // newAppPath = /on-the-edge/app-manager/code-container/executables/1583622378159/app.js
                // generate application's MQTT topic
                let appTopic  = generateTopic(newAppPath);
                let appName = path.basename(newAppPath);

                // Using fork() to create a child process for a new application
                // Using fork() not spawn() is because fork is a special instance of spawn for creating a Nodejs child process.
                // Reference:
                // https://stackoverflow.com/questions/17861362/node-js-child-process-difference-between-spawn-fork
                const newApp = fork(newAppPath, [], {
                    env: { TOPIC: appTopic },
                    stdio: [
                        0,
                        fs.openSync(`${__dirname}/logs/${appName}.out`, 'a'),
                        fs.openSync(`${__dirname}/logs/${appName}.out`, 'a'),
                        "ipc"
                    ]
                });
                // save application's name and pid in mongodb
                saveAppInfoToDB(appTopic, newAppPath, appData.metadataPath, newApp.pid);

                // Stores the process, topic, pid, appPath, and metadataPath in apps
                // application's topic is its id
                apps[appName] = {
                    "app": newApp, // instance of process,
                    "pid": newApp.pid,
                    "topic": appTopic, // application's id
                    "appPath": newAppPath,
                    "metadataPath": appData.metadataPath
                };

                console.log(`[INFO] Launched ${newAppPath} successfully!`);
                console.log(`   time: ${new Date().toISOString()}`);
                console.log(`   path: ${newAppPath}`);
                console.log(`  topic: ${appTopic}`);
                console.log(`    pid: ${newApp.pid}`);
                // sends application's information and metadata to sensor-stream-manager
                // for registering the topic and sensor data requirement.
                messagingService.forwardMessage(serviceName, "sensor-stream-manager", "app-deployment", {
                    "app": apps[appName],
                });
            })
            .catch(err => console.error(err));
    }
});